# Generated by Django 4.1.3 on 2022-11-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Устройство'),
            preserve_default=False,
        ),
    ]
